#ifndef SIMPLE_COIL_MSG_H
#define SIMPLE_COIL_MSG_H

#define MESSAGE_PREFIX "SimpleCoil:"
#define NETWORK_VERSION "06"
#define TCPMESSAGE_PREFIX "SimpleCoil:06"
#define TCPPREFIX_MESG "MESG"
#define TCPPREFIX_JSON "JSON"


// All of these messages are straightforward and contain no extra data
#define NETMSG_SHOTFIRED "SHOTFIRED"
#define NETMSG_HIT "HIT"
#define NETMSG_OUT "OUT"
#define NETMSG_ELIMINATED "ELIMINATED"
#define NETMSG_LEAVE "LEAVE"
#define NETMSG_STARTGAME "STARTGAME"
#define NETMSG_ENDGAME "ENDGAME"
#define NETMSG_ERROR "ERROR"
#define NETMSG_FAILEDTOJOIN "FAILEDTOJOIN"
#define NETMSG_VERSIONERROR "VERSIONERROR"
#define NETMSG_SAMETEAM "SAMETEAM"
#define NETMSG_SERVERCREATED "SERVERCREATED"
#define NETMSG_SERVERCANCEL "SERVERCANCEL"
#define NETMSG_TEAMELIMINATED "TEAMELIMINATED"
#define NETMSG_SERVERREPLY "SERVERREPLY"
#define NETMSG_GPSLOCUPDATE "GPSLOCUPDATE"
#define NETMSG_GPSDATAUPDATE "GPSDATAUPDATE"
#define NETMSG_GPSSETTING "GPSSETTING"
#define NETMSG_PLAYERDATAUPDATE "PLAYERDATAUPDATE"
#define NETMSG_PLAYERDATAREQUEST "PLAYERDATAREQUEST"
#define NETMSG_NETWORKCONNECTED "NETWORKCONNECTED"
#define NETMSG_NETWORKDISCONNECTED "NETWORKDISCONNECTED"
#define NETMSG_PLAYERSETTINGSUPDATE "PLAYERSETTINGSUPDATE"

// When players join a game in progress, the server can send the player updates on appropriate values.
// These items are intent extras.
#define INTENT_HASGAMEUPDATE "HASGAMEUPDATE"
#define INTENT_SCORE "SCORE"
#define INTENT_TEAMSCORE "TEAMSCORE"
#define INTENT_ELIMINATIONS "ELIMINATIONS"
#define INTENT_TIMEREMAINING "TIMEREMAINING"
#define INTENT_GAMESTATE "GAMESTATE"
#define INTENT_LONGITUDE "longitude"
#define INTENT_LATITUDE "latitude"
#define INTENT_FULLUPDATE "fullupdate"
#define INTENT_PLAYERDATA "playerdata"
// UDPJOIN is UDPJOIN + playerID, so UDPJOIN2 for playerID 2
#define NETMSG_JOIN "JOIN"
#define NETMSG_LISTPLAYERS "LISTPLAYERS"

#endif